/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.konversisuhu;

/**
 *
 * @author MyBook Hype
 */
public class app extends javax.swing.JFrame {

    /**
     * Creates new form app
     */
    public app() {
        initComponents();
        reset();
    }
    void reset(){
        tsuhuasal.setText("");
        vhasil.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        psuhuasal = new javax.swing.JPanel();
        tskalaasal = new javax.swing.JComboBox<>();
        tsuhuasal = new javax.swing.JTextField();
        tkonversi = new javax.swing.JPanel();
        tskalatujuan = new javax.swing.JComboBox<>();
        bkonversi = new javax.swing.JButton();
        breset = new javax.swing.JButton();
        bclose = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        vhasil = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentMoved(java.awt.event.ComponentEvent evt) {
                formComponentMoved(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel1.setText("KONVERSI SUHU");

        psuhuasal.setBorder(javax.swing.BorderFactory.createTitledBorder("suhu asal"));

        tskalaasal.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "celcius", "kelvin", "fahrenheit" }));

        javax.swing.GroupLayout psuhuasalLayout = new javax.swing.GroupLayout(psuhuasal);
        psuhuasal.setLayout(psuhuasalLayout);
        psuhuasalLayout.setHorizontalGroup(
            psuhuasalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(psuhuasalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(psuhuasalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tskalaasal, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tsuhuasal))
                .addContainerGap())
        );
        psuhuasalLayout.setVerticalGroup(
            psuhuasalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, psuhuasalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tsuhuasal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addComponent(tskalaasal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        tkonversi.setBorder(javax.swing.BorderFactory.createTitledBorder("konversi ke"));

        tskalatujuan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "celcius", "kelvin", "fahrenheit" }));
        tskalatujuan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tskalatujuanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout tkonversiLayout = new javax.swing.GroupLayout(tkonversi);
        tkonversi.setLayout(tkonversiLayout);
        tkonversiLayout.setHorizontalGroup(
            tkonversiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tkonversiLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tskalatujuan, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        tkonversiLayout.setVerticalGroup(
            tkonversiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tkonversiLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(tskalatujuan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        bkonversi.setText("KONVERSI");
        bkonversi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bkonversiActionPerformed(evt);
            }
        });

        breset.setText("reset");
        breset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bresetActionPerformed(evt);
            }
        });

        bclose.setText("close");
        bclose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bcloseActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder("hasil")));
        jPanel1.setLayout(new java.awt.BorderLayout());

        vhasil.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        vhasil.setText("jLabel2");
        jPanel1.add(vhasil, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(149, 149, 149)
                                .addComponent(jLabel1))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(80, 80, 80)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(bkonversi, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(breset)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(bclose))
                                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tkonversi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(psuhuasal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(118, 118, 118))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(psuhuasal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tkonversi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bkonversi)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(breset)
                    .addComponent(bclose))
                .addGap(57, 57, 57))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bcloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bcloseActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_bcloseActionPerformed

    private void tskalatujuanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tskalatujuanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tskalatujuanActionPerformed

    private void bresetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bresetActionPerformed
        // TODO add your handling code here:
        reset();
    }//GEN-LAST:event_bresetActionPerformed

    private void bkonversiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bkonversiActionPerformed
        // TODO add your handling code here:
        double suhuasal = Double.parseDouble(tsuhuasal.getText());
        String skalasal = tskalaasal.getSelectedItem().toString();
        String skalatujuan = tskalatujuan.getSelectedItem().toString();
        double hasil = 0;
        
        if(skalasal.equals("celcius") && skalatujuan.equals("celcius")){
            hasil = suhuasal;
        }else if(skalasal.equals("celcius") && skalatujuan.equals("kelvin")){
            hasil = suhuasal + 273.15;
        }else if(skalasal.equals("celcius") && skalatujuan.equals("fahrenheit")){
            hasil = suhuasal * 9/5 + 32;
        }else if(skalasal.equals("kelvin") && skalatujuan.equals("kelvin")){
            hasil = suhuasal;
        }else if(skalasal.equals("kelvin") && skalatujuan.equals("celcius")){
            hasil = suhuasal - 273.15;
        }else if(skalasal.equals("kelvin") && skalatujuan.equals("fahrenheit")){
            hasil = (suhuasal - 273.15) * 9/5 + 32;
        }else if(skalasal.equals("fahrenheit") && skalatujuan.equals("fahrenheit")){
            hasil = suhuasal;
        }else if(skalasal.equals("fahrenheit") && skalatujuan.equals("celcius")){
            hasil = (suhuasal - 32) * 5/9;
        }else if(skalasal.equals("fahrenheit") && skalatujuan.equals("kelvin")){
            hasil = (suhuasal - 32) *5/9 + 273.15;
        }
        String skala = skalatujuan.substring(0,1);
        vhasil.setText(String.format("%.2f", hasil) + " \u00B0" + skala);
    }//GEN-LAST:event_bkonversiActionPerformed

    private void formComponentMoved(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentMoved
        // TODO add your handling code here:
        this.setLocationRelativeTo(null);
    }//GEN-LAST:event_formComponentMoved

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(app.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(app.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(app.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(app.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new app().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bclose;
    private javax.swing.JButton bkonversi;
    private javax.swing.JButton breset;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel psuhuasal;
    private javax.swing.JPanel tkonversi;
    private javax.swing.JComboBox<String> tskalaasal;
    private javax.swing.JComboBox<String> tskalatujuan;
    private javax.swing.JTextField tsuhuasal;
    private javax.swing.JLabel vhasil;
    // End of variables declaration//GEN-END:variables
}
